export interface CLIProxyModel {
  readonly id: string
  readonly name?: string
}

export function renderCLIProxyConfig(options: {
  readonly port: number
  readonly authDir: string
  readonly apiKey: string
  readonly managementKey: string
}): string {
  return `host: "127.0.0.1"
port: ${options.port}
auth-dir: ${JSON.stringify(options.authDir)}
api-keys:
  - ${JSON.stringify(options.apiKey)}
remote-management:
  allow-remote: false
  secret-key: ${JSON.stringify(options.managementKey)}
  disable-control-panel: true
logging-to-file: false
usage-statistics-enabled: false
`
}

export function renderHarnessProxyPatch(
  baseURL: string,
  models: readonly CLIProxyModel[],
): string {
  const unique = uniqueModels(models)
  const modelRows = unique.map((model) => {
    const name = model.name && model.name !== model.id
      ? `\n          name: ${JSON.stringify(model.name)}`
      : ''
    return `        - id: ${JSON.stringify(model.id)}${name}`
  }).join('\n')
  const firstModel = unique[0]
  if (!firstModel) throw new Error('Cannot configure Harness without a model')
  return `# Generated by the desktop CLIProxyAPI integration.
- id: llm-pi-ai
  config:
    providers:
      connected-subscriptions:
        displayName: Connected subscriptions
        apiKeyEnv: CLIPROXY_API_KEY
        api: openai-responses
        baseURL: ${JSON.stringify(baseURL)}
        models:
${modelRows}

- id: agent-default-model
  config:
    provider: connected-subscriptions
    model: ${JSON.stringify(firstModel.id)}
`
}

function uniqueModels(models: readonly CLIProxyModel[]): CLIProxyModel[] {
  const seen = new Set<string>()
  return models.filter((model) => {
    if (!model.id || seen.has(model.id)) return false
    seen.add(model.id)
    return true
  })
}
